language: android

jdk:
  - oraclejdk8

before_script:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  ./gradlew test

after_success:
  - .buildscript/deploy_snapshot.sh

sudo: false

cache:
  directories:
    - $HOME/.gradle
